stages:
    - build
    - deploy
    
build-python-2:
    stage: build
    tags:
        - x86
    script:
        - cd alidron-base-python:2
        - make build
    
build-python-2-slim:
    stage: build
    tags:
        - x86
    script:
        - cd alidron-base-python:2-slim
        - make build
    
build-python-2-alpine:
    stage: build
    tags:
        - x86
    script:
        - cd alidron-base-python:2-alpine
        - make build
    
build-rpi-python-2:
    stage: build
    tags:
        - rpi
    script:
        - cd rpi-alidron-base-python:2
        - make build
        
deploy-python-2:
    stage: deploy
    tags:
        - x86
    script:
        - cd alidron-base-python:2
        - make push
        
deploy-python-2-slim:
    stage: deploy
    tags:
        - x86
    script:
        - cd alidron-base-python:2-slim
        - make push
        
deploy-python-2-alpine:
    stage: deploy
    tags:
        - x86
    script:
        - cd alidron-base-python:2-alpine
        - make push
        
deploy-rpi-python-2:
    stage: deploy
    tags:
        - rpi
    script:
        - cd rpi-alidron-base-python:2
        - make push
        
deploy-priv-rpi-python-2:
    stage: deploy
    tags:
        - rpi
    script:
        - cd rpi-alidron-base-python:2
        - make push-priv
