# Copyright (c) 2015-2016 Contributors as noted in the AUTHORS file
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

FROM python:3
MAINTAINER Axel Voitier <axel.voitier@gmail.com>

RUN pip install cython
RUN pip install eventlet
RUN pip install pyzmq
RUN pip install https://github.com/zeromq/pyre/archive/master.zip
RUN pip install pebble
RUN pip install https://github.com/aglyzov/netcall/archive/master.zip
