FROM python:3
MAINTAINER Axel Voitier <axel.voitier@gmail.com>

RUN pip install cython
RUN pip install eventlet
RUN pip install pyzmq
RUN pip install https://github.com/zeromq/pyre/archive/master.zip
RUN pip install pebble
RUN pip install https://github.com/aglyzov/netcall/archive/master.zip
