name: Docker Image CI

on: [push]

env:
  IMAGE_NAME: alidron-base-python

jobs:

  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v1
    - name: Build Docker images
      run: |
        cd alidron-base-python:3-slim
        make build
        
    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} -- password-stdin
    
    - name: Push images
      run: |
        IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
        VERSION=3-slim
        
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        
        docker tag image $IMAGE_NAME:$VERSION $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
